### ISSUE TITLE
Rails 4 digest-only assets

### ISSUE THREAD

**Issue by nathany** [mwanji/jscolor-rails#3]
Rails 4 only generates assets with digests, so the images need to be in the public folder or the JS would need to change (js.erb?) to accomodate.

**Comment by mwanji** [comment]
I'm not sure I understand. Do you mean after assets have been precompiled?

**Comment by mwanji** [comment]
@nathany Could you try the [precompilation branch](https://github.com/mwanji/jscolor-rails/tree/precompilation) and see if that works for you?

I read the [discussion](https://github.com/rails/rails/pull/7968) of the behaviour change and took a workaround from [here](https://dowdrake.com/posts/8-rails-4-0-creating-a-gem-with-image-assets).

**Comment by nathany** [comment]
@mwanji I gave it a try but it didn't work for me.
![404](https://f.cloud.github.com/assets/4566/2101717/97b10cfe-8f55-11e3-93d6-f26901954fe2.png)

The problem is our images are up at oursubdomain.cloudfront.net/assets with names like `hs-3209dfaa457deb8661f5cb4033ba269b.png` (digests). The asset pipeline in Rails 4 doesn't keep the `hs.png` around, so the JavaScript code would need to be aware of the digest filename (perhaps via `image_tag` in ERB, though that may have its own problems).

The alternative is to not use the asset pipeline at all, and my solution for now. We just copy the files to our `public/` folder and let jscolor.js find them there (we're not actually using your gem in this case). This way the filenames continue to be `hs.png`, etc. rather than using the digest names.

**Comment by mwanji** [comment]
I'm working on fixing that by generating versions of the assets without the
digest.

**Comment by mwanji** [comment]
It should work now. Please try again.

**Comment by nathany** [comment]
Sorry, I didn't have a chance to try it again today.

**Comment by mwanji** [comment]
No worries. Let me know when you have a chance to try it out. If it works for you, I'll merge it into master.

**Comment by nathany** [comment]
It's working in our staging environment. Thanks @mwanji.

**Comment by mwanji** [comment]
Great. I've pushed version 1.4.2.1 to RubyGems. Thanks for all your help!

**Comment by nathany** [comment]
Thank you @mwanji.
